version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "06:00"
      timezone: "Europe/Istanbul"
    open-pull-requests-limit: 10
    target-branch: "dev"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "dev"

  - package-ecosystem: "npm"
    directory: "/functions"
    schedule:
      interval: "weekly"
    target-branch: "dev"
